import mysql.connector
from mysql.connector import errorcode

try
    conn = mysql.connector.connect(user = root,
        passwd = 123456,
        host = localhost,
        database = world)

    cur = conn.cursor()
    
    cityName = Kabol
    

    cur.execute(fcall sp_Check_ClientExists({});
                   SELECT @bFound; 
                 )

    result = cur.fetchone()[0]

    print(fThe found value {result})

    cur.close()
    conn.close()

       
except mysql.connector.Error as err
    if err.errno == errorcode.ER_ACCESS_DENIED_ERROR
        print(Incorrect user name or password!)
    elif err.errno == errorcode.ER_BAD_DB_ERROR
        print(Database does not exists)
    else
        print(err)